# Python 

## Numpy使用记录:

In [3]:
import numpy as np
# 使用array函数创建数组，它接受一切序列型的对象（包括其他数组），例如list对象
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print arr1
print type(arr1)

[ 6.   7.5  8.   0.   1. ]
<type 'numpy.ndarray'>


In [6]:
#嵌套序列（比如由一组等长列表组成的列表）将会被转化为一个多维数组
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
#数组维度
print arr2.ndim
#数组形状
print arr2.shape
#np.array会尝试为新建的数组推断出一个合适的数据类型，可调用数组对象的dtype对象
print arr1.dtype
print arr2.dtype
print arr2
print type(arr2)

2
(2, 4)
float64
int64
[[1 2 3 4]
 [5 6 7 8]]
<type 'numpy.ndarray'>


In [10]:
#除了np.array之外，还有一些函数也可以新建数组，例如，zeros，ones和empty，使用这些函数，只需传入哟个表示形状的
#元组就行
print np.zeros(10)
print np.zeros((2,3))
print np.ones((3,3))
#输出的并不是全0
print np.empty((4,4))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  6.90381976e-310   1.14025924e-316   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  9.83448340e-317   1.63041663e-322   6.90381976e-310   1.13271782e-316]]


In [14]:
#arange是python内置函数range的数组版
print np.arange(15)
print np.arange(0,15)
print np.arange(2,15,2)
print type(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
<type 'numpy.ndarray'>


In [16]:
#dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息
#在存储数据量比较大的时候，要控制数据的存储类型
arr3 = np.array([1, 2, 3], dtype = np.float64) #双精度浮点型。占用8字节即64位
arr4 = np.array([1, 2, 3], dtype = np.int32) 
print arr3.dtype
print arr4.dtype
#可以通过ndarray的astype方法显式地转换其dtype
arr5 = np.array([1, 2, 3, 4, 5], dtype = np.int64)
float_arr5 = arr5.astype(np.float64)
print float_arr5.dtype
#也可以将字符串数组（字符是数字，例如‘3‘）通过astype转换为数字
number_strings = np.array(['2', '3', '4'], dtype = np.string_ )
print number_strings.astype(np.float)

float64
int32
float64
[ 2.  3.  4.]


In [18]:
#大小相等的数组之间的任何算术运算都会应用到元素级
arr6 = np.array([[1, 2, 3], [4, 5, 6]])
print arr6*arr6
print arr6+arr6
#同样，数组和标量的算术运算也会将那个标量值传播到各个元素
print 1/arr6
print arr6*0.5

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1 0 0]
 [0 0 0]]
[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]]


In [21]:
#一维数组的索引和切片很简单和python的列表差不多
arr7 = np. arange(10)
print arr7
print arr7[5]
print arr7[5:8]
arr7[5:8] = 12 #将一个标量值赋值给一个切片时，该值会自动传播到整个选区
print arr7
#数组的切片是原始数组的视图，任何在视图中的修改都会直接反映到原始数组中
arr_slice = arr7[5:8]
arr_slice[1] = 12345
print arr_slice
print arr7
arr_slice[:] = 64
print arr7
#由于Numpy的设计目的是处理打数据，假如numpy坚持要将数据来回复制，那将会产生何等的性能和内存问题
#如果你想得到的是ndarray切片的一份副本而非视图，就需要显示地进行复制操作，例如arr5[5:8].copy()

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]
[ 0  1  2  3  4 64 64 64  8  9]
